-- MySQL Script generated by MySQL Workbench
-- 10/21/15 13:52:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdinversiones
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdinversiones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdinversiones` DEFAULT CHARACTER SET latin1 COLLATE latin1_spanish_ci ;
USE `bdinversiones` ;

-- -----------------------------------------------------
-- Table `bdinversiones`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdinversiones`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cedula` VARCHAR(15) NOT NULL COMMENT '',
  `nombre` VARCHAR(50) NOT NULL COMMENT '',
  `telefono` VARCHAR(15) NOT NULL COMMENT '',
  `correo` VARCHAR(50) NOT NULL COMMENT '',
  `direccion` VARCHAR(100) NOT NULL COMMENT '',
  `password` VARCHAR(20) NOT NULL COMMENT '',
  `tipoUsuario` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`idUsuario`)  COMMENT '',
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdinversiones`.`TipoGasto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdinversiones`.`TipoGasto` (
  `idTipoGasto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(30) NOT NULL COMMENT '',
  `descripcion` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`idTipoGasto`)  COMMENT '',
  UNIQUE INDEX `idTipoGasto_UNIQUE` (`idTipoGasto` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdinversiones`.`Gasto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdinversiones`.`Gasto` (
  `idGasto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo` VARCHAR(50) NOT NULL COMMENT '',
  `valor` INT NOT NULL COMMENT '',
  `fecha` DATETIME NOT NULL COMMENT '',
  `descripcion` VARCHAR(100) NULL COMMENT '',
  `idUsuario` INT NOT NULL COMMENT '',
  `idTipoGasto` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idGasto`, `idUsuario`, `idTipoGasto`)  COMMENT '',
  UNIQUE INDEX `idGasto_UNIQUE` (`idGasto` ASC)  COMMENT '',
  INDEX `fk_Gasto_Usuario_idx` (`idUsuario` ASC)  COMMENT '',
  INDEX `fk_Gasto_TipoGasto1_idx` (`idTipoGasto` ASC)  COMMENT '',
  CONSTRAINT `fk_Gasto_Usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `bdinversiones`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gasto_TipoGasto1`
    FOREIGN KEY (`idTipoGasto`)
    REFERENCES `bdinversiones`.`TipoGasto` (`idTipoGasto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdinversiones`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdinversiones`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cedula` VARCHAR(15) NOT NULL COMMENT '',
  `nombre` VARCHAR(50) NOT NULL COMMENT '',
  `direccion` VARCHAR(100) NOT NULL COMMENT '',
  `telefono` VARCHAR(15) NOT NULL COMMENT '',
  `correo` VARCHAR(50) NOT NULL COMMENT '',
  `nombreEmpresa` VARCHAR(50) NULL COMMENT '',
  `direccionEmpresa` VARCHAR(100) NULL COMMENT '',
  `estado` VARCHAR(30) NOT NULL COMMENT '',
  `calificacion` VARCHAR(200) NULL COMMENT '',
  PRIMARY KEY (`idCliente`)  COMMENT '',
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdinversiones`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdinversiones`.`Factura` (
  `idFactura` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fecha` DATETIME NOT NULL COMMENT '',
  `total` INT NOT NULL COMMENT '',
  `fechaCobro` DATETIME NULL COMMENT '',
  `diaCorbo` VARCHAR(10) NULL COMMENT '',
  `horaCobro` VARCHAR(15) NULL COMMENT '',
  `idVendedor` INT NOT NULL COMMENT '',
  `idCliente` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idFactura`, `idVendedor`, `idCliente`)  COMMENT '',
  UNIQUE INDEX `idFactura_UNIQUE` (`idFactura` ASC)  COMMENT '',
  INDEX `fk_Factura_Usuario1_idx` (`idVendedor` ASC)  COMMENT '',
  INDEX `fk_Factura_Cliente1_idx` (`idCliente` ASC)  COMMENT '',
  CONSTRAINT `fk_Factura_Usuario1`
    FOREIGN KEY (`idVendedor`)
    REFERENCES `bdinversiones`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `bdinversiones`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdinversiones`.`Cobro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdinversiones`.`Cobro` (
  `idCobro` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fecha` DATETIME NOT NULL COMMENT '',
  `abono` INT NOT NULL COMMENT '',
  `idVendedor` INT NOT NULL COMMENT '',
  `idFactura` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idCobro`, `idVendedor`, `idFactura`)  COMMENT '',
  UNIQUE INDEX `idCobro_UNIQUE` (`idCobro` ASC)  COMMENT '',
  INDEX `fk_Cobro_Usuario1_idx` (`idVendedor` ASC)  COMMENT '',
  INDEX `fk_Cobro_Factura1_idx` (`idFactura` ASC)  COMMENT '',
  CONSTRAINT `fk_Cobro_Usuario1`
    FOREIGN KEY (`idVendedor`)
    REFERENCES `bdinversiones`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cobro_Factura1`
    FOREIGN KEY (`idFactura`)
    REFERENCES `bdinversiones`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdinversiones`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdinversiones`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(30) NOT NULL COMMENT '',
  `descripcion` VARCHAR(200) NULL COMMENT '',
  PRIMARY KEY (`idCategoria`)  COMMENT '',
  UNIQUE INDEX `idCategoria_UNIQUE` (`idCategoria` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdinversiones`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdinversiones`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(50) NOT NULL COMMENT '',
  `descripcion` VARCHAR(100) NOT NULL COMMENT '',
  `cantidad` INT NOT NULL COMMENT '',
  `precioCompra` INT NOT NULL COMMENT '',
  `precioVenta` INT NOT NULL COMMENT '',
  `idCategoria` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idProducto`, `idCategoria`)  COMMENT '',
  UNIQUE INDEX `idProducto_UNIQUE` (`idProducto` ASC)  COMMENT '',
  INDEX `fk_Producto_Categoria1_idx` (`idCategoria` ASC)  COMMENT '',
  CONSTRAINT `fk_Producto_Categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `bdinversiones`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdinversiones`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdinversiones`.`Venta` (
  `idVenta` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `total` INT NOT NULL COMMENT '',
  `cantidad` INT NOT NULL COMMENT '',
  `estado` VARCHAR(30) NOT NULL COMMENT '',
  `idFactura` INT NOT NULL COMMENT '',
  `idProducto` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idVenta`, `idFactura`, `idProducto`)  COMMENT '',
  UNIQUE INDEX `idVenta_UNIQUE` (`idVenta` ASC)  COMMENT '',
  INDEX `fk_Venta_Factura1_idx` (`idFactura` ASC)  COMMENT '',
  INDEX `fk_Venta_Producto1_idx` (`idProducto` ASC)  COMMENT '',
  CONSTRAINT `fk_Venta_Factura1`
    FOREIGN KEY (`idFactura`)
    REFERENCES `bdinversiones`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `bdinversiones`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
